<?php

namespace Derasy\DerasyBundle\Tests;

use Derasy\DerasyBundle\DerasyGreeting;
use Derasy\DerasyBundle\DerasyBundle;

use Derasy\DerasyBundle\SalamUmumList;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel;

class FunctionalTest extends TestCase

{
    public function testServiceWiring()
    {
        $kernel = new DerasyTestingKernel();
        $kernel->boot();
        $container = $kernel->getContainer();

        $derasy = $container->get('derasy_bundle.derasy_greeting');
        $this->assertInstanceOf(DerasyGreeting::class, $derasy);
        $this->assertInternalType('string', $derasy->getGreeting());
    }

    public function testServiceWiringWithConfiguration()
    {
        $kernel = new DerasyTestingKernel([
            'salam_provider' => 'salam_umum_list'
        ]);
        $kernel->boot();
        $container = $kernel->getContainer();


        $derasy = $container->get('derasy_bundle.derasy_greeting');
        $this->assertContains('Selamat pagi', $derasy->getSalamList());
    }
}

class DerasyTestingKernel extends Kernel
{
    private $derasyConfig;

    public function __construct(array $derasyConfig = [])
    {
        $this->derasyConfig = $derasyConfig;
        parent::__construct('test', true);
    }

    public function registerBundles()
    {
        return [
            new DerasyBundle(),
        ];
    }
    
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load(function(ContainerBuilder $container){
            $container->register('salam_umum_list', SalamUmumList::class);
            $container->loadFromExtension('derasy', $this->derasyConfig);
        });
    }

    public function getCacheDir()
    {
        // return parent::getCacheDir(); // TODO: Change the autogenerated stub
        return __DIR__.'/cache/'.spl_object_hash($this);
    }


}